language: node_js
node_js:
  - "4.2.0"
  - "5"
  - "6"
before_script:
  - "echo '{ \"token\": \"'$GH_TOKEN'\" }' > ~/.tsdrc"
  - npm install -g gulp-cli mocha istanbul coveralls
after_script:
  - npm run coveralls